# Generated by Django 4.2.4 on 2024-06-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Responder', 'responder'), ('Hospital', 'hospital'), ('Vehicle', 'vehicle')], default='Responder', max_length=20),
        ),
    ]
