# Generated by Django 4.2.13 on 2024-11-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Responder', 'responder'), ('Vehicle', 'vehicle')], default='Responder', max_length=20),
        ),
    ]
