# Generated by Django 4.2.4 on 2024-06-04 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidence',
            name='call',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.calls'),
        ),
    ]
