# Generated by Django 4.2.4 on 2024-06-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_alter_incidence_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidence',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], default='pending', max_length=50),
        ),
    ]
