# Generated by Django 4.2.4 on 2024-06-06 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0004_alter_incidence_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='responders',
            field=models.ManyToManyField(related_name='response', to=settings.AUTH_USER_MODEL),
        ),
    ]
